{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bloggy.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "bloggy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - web
  routes:
  {{- range .Values.ingress.hosts }}
  - match: Host(`{{ .host }}`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
  {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-tls
  labels:
    {{- include "bloggy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - websecure
  routes:
  {{- range .Values.ingress.hosts }}
  - match: Host(`{{ .host }}`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
  {{- end }}
  tls:
    certResolver: default
{{- end }}
